function createfigure2(ymatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 07-May-2016 09:59:37

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1,'XTick',[1 2 3]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);
set(bar1(1),'DisplayName','% of Sent Notifications');
set(bar1(2),'DisplayName','% of Messages in Recycling Bin');
set(bar1(3),'DisplayName','% of Messages in Queue');

% Create title
title('Percentage Values of Decisions Classified by Priority');

% Create xlabel
xlabel('Priority');

% Create ylabel
ylabel('Percentage (%)');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.504022385449458 0.80618975139523 0.23189926547744 0.0923389142567225]);

