function createfigure(ymatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  stem matrix data

%  Auto-generated by MATLAB on 05-May-2016 12:15:30

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[90 90]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to stem
stem1 = stem(ymatrix1,'MarkerSize',10,'Parent',axes1);
set(stem1(1),'MarkerFaceColor',[1 0 0],'MarkerEdgeColor',[1 0 0],...
    'Marker','>',...
    'LineStyle','none',...
    'DisplayName','Sent');
set(stem1(2),'LineStyle','--','LineWidth',2,'DisplayName','Arrived');

% Create title
title('Arrival and Sending Time for Notifications');

% Create xlabel
xlabel('Incoming Message','VerticalAlignment','bottom','Rotation',90,...
    'HorizontalAlignment','center');

% Create ylabel
ylabel('Time (Seconds)','VerticalAlignment','cap',...
    'HorizontalAlignment','center');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthEast');

